package com.mudounet.hibernate.tags;

/**
 * Tag generated by hbm2java
* @hibernate.subclass
* discriminator-value="T"
*/
public class Tag extends GenericTag implements java.io.Serializable {


     /**
      * Value of this tag
     */
     private String value;

     public Tag() {
    }


    public Tag(String key) {
        super(key);        
    }
   
    /**
    * @hibernate.property
    */
    public String getValue() {
        return this.value;
    }
    
    public void setValue(String value) {
        this.value = value;
    }




}


