package hibernate;
// Generated 3 janv. 2011 12:49:11 by Hibernate Tools 3.2.0.b9



/**
 * TechData generated by hbm2java
 */
public class TechData  implements java.io.Serializable {


     private int id;
     /**
      * Playing time (milliseconds)
     */
     private long playTime;
     /**
      * Path of file
     */
     private String path;
     /**
      * Path of file
     */
     private int filesize;
     /**
      * MD5 sum
     */
     private String md5Sum;
     /**
      * Width of movie in pixel
     */
     private int width;
     /**
      * Width of movie in pixel
     */
     private int height;

    public TechData() {
    }

	
    public TechData(String path) {
        this.path = path;
    }
    public TechData(long playTime, String path, int filesize, String md5Sum, int width, int height) {
       this.playTime = playTime;
       this.path = path;
       this.filesize = filesize;
       this.md5Sum = md5Sum;
       this.width = width;
       this.height = height;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    /**       
     *      * Playing time (milliseconds)
     */
    public long getPlayTime() {
        return this.playTime;
    }
    
    public void setPlayTime(long playTime) {
        this.playTime = playTime;
    }
    /**       
     *      * Path of file
     */
    public String getPath() {
        return this.path;
    }
    
    public void setPath(String path) {
        this.path = path;
    }
    /**       
     *      * Path of file
     */
    public int getFilesize() {
        return this.filesize;
    }
    
    public void setFilesize(int filesize) {
        this.filesize = filesize;
    }
    /**       
     *      * MD5 sum
     */
    public String getMd5Sum() {
        return this.md5Sum;
    }
    
    public void setMd5Sum(String md5Sum) {
        this.md5Sum = md5Sum;
    }
    /**       
     *      * Width of movie in pixel
     */
    public int getWidth() {
        return this.width;
    }
    
    public void setWidth(int width) {
        this.width = width;
    }
    /**       
     *      * Width of movie in pixel
     */
    public int getHeight() {
        return this.height;
    }
    
    public void setHeight(int height) {
        this.height = height;
    }

    /**
     * toString
     * @return String
     */
     public String toString() {
	  StringBuffer buffer = new StringBuffer();

      buffer.append(getClass().getName()).append("@").append(Integer.toHexString(hashCode())).append(" [");
      buffer.append("playTime").append("='").append(getPlayTime()).append("' ");			
      buffer.append("width").append("='").append(getWidth()).append("' ");			
      buffer.append("height").append("='").append(getHeight()).append("' ");			
      buffer.append("]");
      
      return buffer.toString();
     }



}


