package hibernate.image;
// Generated 3 janv. 2011 12:49:11 by Hibernate Tools 3.2.0.b9



/**
 * Index generated by hbm2java
 */
public class Index extends hibernate.image.Image implements java.io.Serializable {



    public Index() {
    }

    public Index(String path, String md5sum, int offset) {
        super(path, md5sum, offset);        
    }
   




}


