package hibernate.image;
// Generated 3 janv. 2011 12:49:11 by Hibernate Tools 3.2.0.b9



/**
 * Thumbnail generated by hbm2java
 */
public class Thumbnail extends hibernate.image.Image implements java.io.Serializable {



    public Thumbnail() {
    }

    public Thumbnail(String path, String md5sum, int offset) {
        super(path, md5sum, offset);        
    }
   




}


