/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * MainFrame.java
 *
 * Created on 2 déc. 2010, 18:57:51
 */

package ui;

import javax.swing.JList;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

/**
 *
 * @author gmanciet
 */
public class MainFrame1 extends javax.swing.JFrame {
    private static Logger logger = LoggerFactory.getLogger(MainFrame1.class.getName());

    /** Creates new form MainFrame */
    public MainFrame1() {
        initComponents();
        this.jListMovie.setLayoutOrientation(JList.HORIZONTAL_WRAP);
        // Set the item width
    int cellWidth = 200;
    this.jListMovie.setFixedCellWidth(cellWidth);

    // Set the item height
    int cellHeight = 200;
    this.jListMovie.setFixedCellHeight(cellHeight);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        jSFilters = new javax.swing.JScrollPane();
        jTFilters = new javax.swing.JTree();
        jScrollRight = new javax.swing.JScrollPane();
        jListMovie = new javax.swing.JList();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMActions = new javax.swing.JMenu();
        jMAddFolder = new javax.swing.JMenuItem();
        jMExit = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jSplitPane1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jSplitPane1.setDividerLocation(130);
        jSplitPane1.setDividerSize(0);
        jSplitPane1.setEnabled(false);

        jTFilters.setAutoscrolls(true);
        jTFilters.setRootVisible(false);
        jSFilters.setViewportView(jTFilters);

        jSplitPane1.setLeftComponent(jSFilters);

        jScrollRight.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollRight.setAutoscrolls(true);

        jListMovie.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jListMovie.setCellRenderer(new ui.thumb.JIListRenderer());
        jScrollRight.setViewportView(jListMovie);

        jSplitPane1.setRightComponent(jScrollRight);

        jMActions.setText("Actions");

        jMAddFolder.setText("Add Folder");
        jMActions.add(jMAddFolder);

        jMExit.setText("Exit");
        jMActions.add(jMExit);

        jMenuBar1.add(jMActions);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 460, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 290, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame1().setVisible(true);
            }
        });
    }

    private void addMovie(String text){
        MoviePanel t = new MoviePanel(text);
        logger.debug("Adding : "+text);

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList jListMovie;
    private javax.swing.JMenu jMActions;
    private javax.swing.JMenuItem jMAddFolder;
    private javax.swing.JMenuItem jMExit;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jSFilters;
    private javax.swing.JScrollPane jScrollRight;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JTree jTFilters;
    // End of variables declaration//GEN-END:variables

}
