/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * MainFrame.java
 *
 * Created on 2 déc. 2010, 18:57:51
 */

package ui;

/**
 *
 * @author gmanciet
 */
public class MainFrame extends javax.swing.JFrame {
    private static final long serialVersionUID = 1L;

    /** Creates new form MainFrame */
    public MainFrame() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        jSplitPane1 = new javax.swing.JSplitPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTMovie = new javax.swing.JTable();
        jSFilters = new javax.swing.JScrollPane();
        jTFilters = new javax.swing.JTree();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMActions = new javax.swing.JMenu();
        jMAddFolder = new javax.swing.JMenuItem();
        jMExit = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jSplitPane1.setBorder(null);
        jSplitPane1.setDividerLocation(130);
        jSplitPane1.setDividerSize(4);
        jSplitPane1.setAutoscrolls(true);
        jSplitPane1.setEnabled(false);
        jSplitPane1.setPreferredSize(new java.awt.Dimension(400, 350));

        jTMovie.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Title", "Duration", "Rating"
            }
        ));
        jScrollPane2.setViewportView(jTMovie);
        jTMovie.getColumnModel().getColumn(1).setMinWidth(50);
        jTMovie.getColumnModel().getColumn(1).setMaxWidth(50);
        jTMovie.getColumnModel().getColumn(2).setMinWidth(40);
        jTMovie.getColumnModel().getColumn(2).setMaxWidth(40);

        jSplitPane1.setBottomComponent(jScrollPane2);

        jTFilters.setAutoscrolls(true);
        jTFilters.setPreferredSize(new java.awt.Dimension(100, 64));
        jTFilters.setRootVisible(false);
        jSFilters.setViewportView(jTFilters);

        jSplitPane1.setLeftComponent(jSFilters);

        jMActions.setText("Actions");

        jMAddFolder.setText("Add Folder");
        jMActions.add(jMAddFolder);

        jMExit.setText("Exit");
        jMActions.add(jMExit);

        jMenuBar1.add(jMActions);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 279, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMActions;
    private javax.swing.JMenuItem jMAddFolder;
    private javax.swing.JMenuItem jMExit;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JScrollPane jSFilters;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JTree jTFilters;
    private javax.swing.JTable jTMovie;
    // End of variables declaration//GEN-END:variables

}